name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres-container:17.1.1
          build-args: |
            PG_MAJOR=17
            ORACLE_VERSION=19.25.0.0.0
          # tags: |          
          #   ${{ secrets.DOCKERHUB_USERNAME }}/postgres-container:latest
          #   ${{ secrets.DOCKERHUB_USERNAME }}/postgres-container:v1.0.0-rc.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository to lowercase
        id: lower-repo
        run: |
          GITHUB_REPOSITORY=${{github.repository_owner}} && 
          echo "repository=${GITHUB_REPOSITORY@L}/postgres-container" >> $GITHUB_OUTPUT

      # - name: Push image to GHCR
      #   run: |
      #     docker buildx imagetools create \
      #       --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:v0.0.1 \
      #       ${{ secrets.DOCKERHUB_USERNAME }}/postgres-container:v0.0.1

      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:17.1.1
          build-args: |
            PG_MAJOR=17
            ORACLE_VERSION=19.25.0.0.0